export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'
export const ACTIVATION_SUCCESS='ACTIVATION_SUCCESS'
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_FAIL = 'PASSWORD_RESET_FAIL';
export const PASSWORD_RESET_CONFIRM_SUCCESS = 'PASSWORD_RESET_CONFIRM_SUCCESS';
export const PASSWORD_RESET_CONFIRM_FAIL = 'PASSWORD_RESET_CONFIRM_FAIL';
export const GOOGLE_AUTH_SUCCESS = 'GOOGLE_AUTH_SUCCESS';
export const GOOGLE_AUTH_FAIL = 'GOOGLE_AUTH_FAIL';
export const FACEBOOK_AUTH_SUCCESS = 'FACEBOOK_AUTH_SUCCESS';
export const FACEBOOK_AUTH_FAIL = 'FACEBOOK_AUTH_FAIL';
export const LOGIN_PAGE = 'LOGIN_PAGE';
export const REGISTRATION_PAGE = 'REGISTRATION_PAGE';
export const SETTING_PAGE ='SETTING_PAGE';
export const LOGOUT = 'LOGOUT';


export const GET_PRODUCT="GET_PRODUCT"
export const GET_PRODUCT_FAIL="GET_PRODUCT_FAIL"
export const FAIL_CART_PRODUCT="FAIL_CART_PRODUCT"

export const GET_CART_PRODUCT="GET_CART_PRODUCT"
export const POST_CART_PRODUCT_SUCCESS="POST_CART_PRODUCT_SUCCESS"
export const DELETE_CART_PRODUCT_SUCCESS="DELETE_CART_PRODUCT_SUCCESS"
export const INCREMENT = "INCREMENT"
export const DECREMENT = "DECREMENT"
export const PUT_CART_PRODUCT_SUCCESS = "PUT_CART_PRODUCT_SUCCESS" 


export const SET_COVER="SET_COVER"

export const CLICKED_PRODUCT='CLICKED_PRODUCT'


export const SHOW_PRODUCT='SHOW_PRODUCT'

export const SHOW_MESSAGE = 'SHOW_MESSAGE'