# Generated by Django 3.2 on 2021-05-31 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='idproduct',
            field=models.IntegerField(default=-1),
        ),
    ]
